"""Check manually adjudicated, explicitly scoped cross-batch answer evidence.

No model calls or automatic truth adjudication. This verifies frozen provenance
and that normal retrieval still supplies each reviewed source window.
"""
import hashlib
import json

from lore_store import ROOT, LoreStore, collection_path, read, windows


def review_digest(case):
    snapshot = {key: case[key] for key in ('question', 'answer', 'sources')}
    return hashlib.sha256(json.dumps(snapshot, sort_keys=True).encode()).hexdigest()


def evaluate(cases=None):
    if cases is None:
        cases = read(ROOT / 'batches/reviews/continuity-cases.json')['cases']
    if len({c['id'] for c in cases}) != len(cases):
        raise ValueError('Duplicate continuity case')
    stores = {}
    results = []
    try:
        for case in cases:
            if not case.get('answer') or case['review']['status'] != 'passed' or not case['review'].get('reason'):
                raise ValueError('Missing actual answer or manual review')
            if case['review'].get('snapshot_sha256') != review_digest(case):
                raise ValueError('Continuity manual review is stale')
            if len({(s['collection'], s['episode']) for s in case['sources']}) < 2:
                raise ValueError('Continuity requires at least two episode sources')
            dates = [s['date'] for s in case['sources']]
            if dates != sorted(dates):
                raise ValueError('Source reports must be chronologically ordered')
            proofs = []
            for source in case['sources']:
                collection = source['collection']
                base = collection_path(ROOT, collection)
                entries = read(base / 'manifest.json')['episodes']
                entry = next(e for e in entries if e['key'] == source['source_key'])
                if entry['episode_number'] != source['episode'] or entry['date'] != source['date']:
                    raise ValueError('Continuity source identity mismatch')
                path = (ROOT / 'library' / entry['path']).resolve()
                if not path.is_relative_to((ROOT / 'library').resolve()):
                    raise ValueError('Source outside library')
                if hashlib.sha256(path.read_bytes()).hexdigest() != source['source_sha256']:
                    raise ValueError('Continuity source changed')
                text = windows(ROOT, entry).get(source['location'], '')
                if not source['quote'] or source['quote'] not in text:
                    raise ValueError('Unsupported continuity quote: ' + case['id'])
                if collection not in stores:
                    stores[collection] = LoreStore(collection=collection)
                packet = stores[collection].answer_evidence(source['query'], source['episode'])
                retrieved = {r['evidence'][0]['location'] for r in packet['context']}
                proofs.append(dict(collection=collection, episode=source['episode'],
                                   location=source['location'], retrieved=source['location'] in retrieved))
            results.append(dict(id=case['id'], passed=all(p['retrieved'] for p in proofs), sources=proofs))
    finally:
        for store in stores.values():
            store.close()
    return dict(total=len(results), passed=sum(r['passed'] for r in results),
                source_checks=sum(len(r['sources']) for r in results), results=results,
                limits='Source/context regression only; semantic answers manually reviewed, not generated by this script.')


if __name__ == '__main__':
    result = evaluate()
    print(json.dumps(result, indent=2))
    raise SystemExit(result['passed'] != result['total'])
